version: '2.1'

services:
  facade:
    build: composer-v1-facade
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  composition:
    build: composer-v1-composition-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
